// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/Messages.proto
// Protobuf Java Version: 4.27.3

package messagemq;

public final class MessageProto {
  private MessageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      MessageProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MensagemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messagemq.Mensagem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Nome do emissor
     * </pre>
     *
     * <code>string emissor = 1;</code>
     * @return The emissor.
     */
    java.lang.String getEmissor();
    /**
     * <pre>
     * Nome do emissor
     * </pre>
     *
     * <code>string emissor = 1;</code>
     * @return The bytes for emissor.
     */
    com.google.protobuf.ByteString
        getEmissorBytes();

    /**
     * <pre>
     * Data de envio
     * </pre>
     *
     * <code>string data = 2;</code>
     * @return The data.
     */
    java.lang.String getData();
    /**
     * <pre>
     * Data de envio
     * </pre>
     *
     * <code>string data = 2;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <pre>
     * Hora de envio
     * </pre>
     *
     * <code>string hora = 3;</code>
     * @return The hora.
     */
    java.lang.String getHora();
    /**
     * <pre>
     * Hora de envio
     * </pre>
     *
     * <code>string hora = 3;</code>
     * @return The bytes for hora.
     */
    com.google.protobuf.ByteString
        getHoraBytes();

    /**
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     *
     * <code>string grupo = 4;</code>
     * @return The grupo.
     */
    java.lang.String getGrupo();
    /**
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     *
     * <code>string grupo = 4;</code>
     * @return The bytes for grupo.
     */
    com.google.protobuf.ByteString
        getGrupoBytes();

    /**
     * <code>.messagemq.Conteudo conteudo = 5;</code>
     * @return Whether the conteudo field is set.
     */
    boolean hasConteudo();
    /**
     * <code>.messagemq.Conteudo conteudo = 5;</code>
     * @return The conteudo.
     */
    messagemq.MessageProto.Conteudo getConteudo();
    /**
     * <code>.messagemq.Conteudo conteudo = 5;</code>
     */
    messagemq.MessageProto.ConteudoOrBuilder getConteudoOrBuilder();
  }
  /**
   * Protobuf type {@code messagemq.Mensagem}
   */
  public static final class Mensagem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:messagemq.Mensagem)
      MensagemOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        Mensagem.class.getName());
    }
    // Use Mensagem.newBuilder() to construct.
    private Mensagem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Mensagem() {
      emissor_ = "";
      data_ = "";
      hora_ = "";
      grupo_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messagemq.MessageProto.internal_static_messagemq_Mensagem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messagemq.MessageProto.internal_static_messagemq_Mensagem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messagemq.MessageProto.Mensagem.class, messagemq.MessageProto.Mensagem.Builder.class);
    }

    private int bitField0_;
    public static final int EMISSOR_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object emissor_ = "";
    /**
     * <pre>
     * Nome do emissor
     * </pre>
     *
     * <code>string emissor = 1;</code>
     * @return The emissor.
     */
    @java.lang.Override
    public java.lang.String getEmissor() {
      java.lang.Object ref = emissor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emissor_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Nome do emissor
     * </pre>
     *
     * <code>string emissor = 1;</code>
     * @return The bytes for emissor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmissorBytes() {
      java.lang.Object ref = emissor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emissor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object data_ = "";
    /**
     * <pre>
     * Data de envio
     * </pre>
     *
     * <code>string data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Data de envio
     * </pre>
     *
     * <code>string data = 2;</code>
     * @return The bytes for data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HORA_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object hora_ = "";
    /**
     * <pre>
     * Hora de envio
     * </pre>
     *
     * <code>string hora = 3;</code>
     * @return The hora.
     */
    @java.lang.Override
    public java.lang.String getHora() {
      java.lang.Object ref = hora_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hora_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Hora de envio
     * </pre>
     *
     * <code>string hora = 3;</code>
     * @return The bytes for hora.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHoraBytes() {
      java.lang.Object ref = hora_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hora_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GRUPO_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object grupo_ = "";
    /**
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     *
     * <code>string grupo = 4;</code>
     * @return The grupo.
     */
    @java.lang.Override
    public java.lang.String getGrupo() {
      java.lang.Object ref = grupo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        grupo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     *
     * <code>string grupo = 4;</code>
     * @return The bytes for grupo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGrupoBytes() {
      java.lang.Object ref = grupo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        grupo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTEUDO_FIELD_NUMBER = 5;
    private messagemq.MessageProto.Conteudo conteudo_;
    /**
     * <code>.messagemq.Conteudo conteudo = 5;</code>
     * @return Whether the conteudo field is set.
     */
    @java.lang.Override
    public boolean hasConteudo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.messagemq.Conteudo conteudo = 5;</code>
     * @return The conteudo.
     */
    @java.lang.Override
    public messagemq.MessageProto.Conteudo getConteudo() {
      return conteudo_ == null ? messagemq.MessageProto.Conteudo.getDefaultInstance() : conteudo_;
    }
    /**
     * <code>.messagemq.Conteudo conteudo = 5;</code>
     */
    @java.lang.Override
    public messagemq.MessageProto.ConteudoOrBuilder getConteudoOrBuilder() {
      return conteudo_ == null ? messagemq.MessageProto.Conteudo.getDefaultInstance() : conteudo_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(emissor_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, emissor_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, data_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hora_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, hora_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(grupo_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, grupo_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(5, getConteudo());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(emissor_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, emissor_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, data_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hora_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, hora_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(grupo_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, grupo_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getConteudo());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof messagemq.MessageProto.Mensagem)) {
        return super.equals(obj);
      }
      messagemq.MessageProto.Mensagem other = (messagemq.MessageProto.Mensagem) obj;

      if (!getEmissor()
          .equals(other.getEmissor())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getHora()
          .equals(other.getHora())) return false;
      if (!getGrupo()
          .equals(other.getGrupo())) return false;
      if (hasConteudo() != other.hasConteudo()) return false;
      if (hasConteudo()) {
        if (!getConteudo()
            .equals(other.getConteudo())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EMISSOR_FIELD_NUMBER;
      hash = (53 * hash) + getEmissor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + HORA_FIELD_NUMBER;
      hash = (53 * hash) + getHora().hashCode();
      hash = (37 * hash) + GRUPO_FIELD_NUMBER;
      hash = (53 * hash) + getGrupo().hashCode();
      if (hasConteudo()) {
        hash = (37 * hash) + CONTEUDO_FIELD_NUMBER;
        hash = (53 * hash) + getConteudo().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static messagemq.MessageProto.Mensagem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messagemq.MessageProto.Mensagem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messagemq.MessageProto.Mensagem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messagemq.MessageProto.Mensagem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messagemq.MessageProto.Mensagem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messagemq.MessageProto.Mensagem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messagemq.MessageProto.Mensagem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static messagemq.MessageProto.Mensagem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static messagemq.MessageProto.Mensagem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static messagemq.MessageProto.Mensagem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static messagemq.MessageProto.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static messagemq.MessageProto.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(messagemq.MessageProto.Mensagem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messagemq.Mensagem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messagemq.Mensagem)
        messagemq.MessageProto.MensagemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messagemq.MessageProto.internal_static_messagemq_Mensagem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messagemq.MessageProto.internal_static_messagemq_Mensagem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messagemq.MessageProto.Mensagem.class, messagemq.MessageProto.Mensagem.Builder.class);
      }

      // Construct using messagemq.MessageProto.Mensagem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getConteudoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        emissor_ = "";
        data_ = "";
        hora_ = "";
        grupo_ = "";
        conteudo_ = null;
        if (conteudoBuilder_ != null) {
          conteudoBuilder_.dispose();
          conteudoBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messagemq.MessageProto.internal_static_messagemq_Mensagem_descriptor;
      }

      @java.lang.Override
      public messagemq.MessageProto.Mensagem getDefaultInstanceForType() {
        return messagemq.MessageProto.Mensagem.getDefaultInstance();
      }

      @java.lang.Override
      public messagemq.MessageProto.Mensagem build() {
        messagemq.MessageProto.Mensagem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public messagemq.MessageProto.Mensagem buildPartial() {
        messagemq.MessageProto.Mensagem result = new messagemq.MessageProto.Mensagem(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(messagemq.MessageProto.Mensagem result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.emissor_ = emissor_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.data_ = data_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.hora_ = hora_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.grupo_ = grupo_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.conteudo_ = conteudoBuilder_ == null
              ? conteudo_
              : conteudoBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messagemq.MessageProto.Mensagem) {
          return mergeFrom((messagemq.MessageProto.Mensagem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messagemq.MessageProto.Mensagem other) {
        if (other == messagemq.MessageProto.Mensagem.getDefaultInstance()) return this;
        if (!other.getEmissor().isEmpty()) {
          emissor_ = other.emissor_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getHora().isEmpty()) {
          hora_ = other.hora_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getGrupo().isEmpty()) {
          grupo_ = other.grupo_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasConteudo()) {
          mergeConteudo(other.getConteudo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                emissor_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                data_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                hora_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                grupo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getConteudoFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object emissor_ = "";
      /**
       * <pre>
       * Nome do emissor
       * </pre>
       *
       * <code>string emissor = 1;</code>
       * @return The emissor.
       */
      public java.lang.String getEmissor() {
        java.lang.Object ref = emissor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          emissor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Nome do emissor
       * </pre>
       *
       * <code>string emissor = 1;</code>
       * @return The bytes for emissor.
       */
      public com.google.protobuf.ByteString
          getEmissorBytes() {
        java.lang.Object ref = emissor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emissor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Nome do emissor
       * </pre>
       *
       * <code>string emissor = 1;</code>
       * @param value The emissor to set.
       * @return This builder for chaining.
       */
      public Builder setEmissor(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        emissor_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nome do emissor
       * </pre>
       *
       * <code>string emissor = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmissor() {
        emissor_ = getDefaultInstance().getEmissor();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nome do emissor
       * </pre>
       *
       * <code>string emissor = 1;</code>
       * @param value The bytes for emissor to set.
       * @return This builder for chaining.
       */
      public Builder setEmissorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        emissor_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>string data = 2;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>string data = 2;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>string data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>string data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = getDefaultInstance().getData();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>string data = 2;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        data_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object hora_ = "";
      /**
       * <pre>
       * Hora de envio
       * </pre>
       *
       * <code>string hora = 3;</code>
       * @return The hora.
       */
      public java.lang.String getHora() {
        java.lang.Object ref = hora_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hora_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Hora de envio
       * </pre>
       *
       * <code>string hora = 3;</code>
       * @return The bytes for hora.
       */
      public com.google.protobuf.ByteString
          getHoraBytes() {
        java.lang.Object ref = hora_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hora_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Hora de envio
       * </pre>
       *
       * <code>string hora = 3;</code>
       * @param value The hora to set.
       * @return This builder for chaining.
       */
      public Builder setHora(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        hora_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Hora de envio
       * </pre>
       *
       * <code>string hora = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHora() {
        hora_ = getDefaultInstance().getHora();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Hora de envio
       * </pre>
       *
       * <code>string hora = 3;</code>
       * @param value The bytes for hora to set.
       * @return This builder for chaining.
       */
      public Builder setHoraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        hora_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object grupo_ = "";
      /**
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       *
       * <code>string grupo = 4;</code>
       * @return The grupo.
       */
      public java.lang.String getGrupo() {
        java.lang.Object ref = grupo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          grupo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       *
       * <code>string grupo = 4;</code>
       * @return The bytes for grupo.
       */
      public com.google.protobuf.ByteString
          getGrupoBytes() {
        java.lang.Object ref = grupo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          grupo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       *
       * <code>string grupo = 4;</code>
       * @param value The grupo to set.
       * @return This builder for chaining.
       */
      public Builder setGrupo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        grupo_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       *
       * <code>string grupo = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGrupo() {
        grupo_ = getDefaultInstance().getGrupo();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       *
       * <code>string grupo = 4;</code>
       * @param value The bytes for grupo to set.
       * @return This builder for chaining.
       */
      public Builder setGrupoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        grupo_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private messagemq.MessageProto.Conteudo conteudo_;
      private com.google.protobuf.SingleFieldBuilder<
          messagemq.MessageProto.Conteudo, messagemq.MessageProto.Conteudo.Builder, messagemq.MessageProto.ConteudoOrBuilder> conteudoBuilder_;
      /**
       * <code>.messagemq.Conteudo conteudo = 5;</code>
       * @return Whether the conteudo field is set.
       */
      public boolean hasConteudo() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.messagemq.Conteudo conteudo = 5;</code>
       * @return The conteudo.
       */
      public messagemq.MessageProto.Conteudo getConteudo() {
        if (conteudoBuilder_ == null) {
          return conteudo_ == null ? messagemq.MessageProto.Conteudo.getDefaultInstance() : conteudo_;
        } else {
          return conteudoBuilder_.getMessage();
        }
      }
      /**
       * <code>.messagemq.Conteudo conteudo = 5;</code>
       */
      public Builder setConteudo(messagemq.MessageProto.Conteudo value) {
        if (conteudoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          conteudo_ = value;
        } else {
          conteudoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.messagemq.Conteudo conteudo = 5;</code>
       */
      public Builder setConteudo(
          messagemq.MessageProto.Conteudo.Builder builderForValue) {
        if (conteudoBuilder_ == null) {
          conteudo_ = builderForValue.build();
        } else {
          conteudoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.messagemq.Conteudo conteudo = 5;</code>
       */
      public Builder mergeConteudo(messagemq.MessageProto.Conteudo value) {
        if (conteudoBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            conteudo_ != null &&
            conteudo_ != messagemq.MessageProto.Conteudo.getDefaultInstance()) {
            getConteudoBuilder().mergeFrom(value);
          } else {
            conteudo_ = value;
          }
        } else {
          conteudoBuilder_.mergeFrom(value);
        }
        if (conteudo_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.messagemq.Conteudo conteudo = 5;</code>
       */
      public Builder clearConteudo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        conteudo_ = null;
        if (conteudoBuilder_ != null) {
          conteudoBuilder_.dispose();
          conteudoBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.messagemq.Conteudo conteudo = 5;</code>
       */
      public messagemq.MessageProto.Conteudo.Builder getConteudoBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getConteudoFieldBuilder().getBuilder();
      }
      /**
       * <code>.messagemq.Conteudo conteudo = 5;</code>
       */
      public messagemq.MessageProto.ConteudoOrBuilder getConteudoOrBuilder() {
        if (conteudoBuilder_ != null) {
          return conteudoBuilder_.getMessageOrBuilder();
        } else {
          return conteudo_ == null ?
              messagemq.MessageProto.Conteudo.getDefaultInstance() : conteudo_;
        }
      }
      /**
       * <code>.messagemq.Conteudo conteudo = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          messagemq.MessageProto.Conteudo, messagemq.MessageProto.Conteudo.Builder, messagemq.MessageProto.ConteudoOrBuilder> 
          getConteudoFieldBuilder() {
        if (conteudoBuilder_ == null) {
          conteudoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              messagemq.MessageProto.Conteudo, messagemq.MessageProto.Conteudo.Builder, messagemq.MessageProto.ConteudoOrBuilder>(
                  getConteudo(),
                  getParentForChildren(),
                  isClean());
          conteudo_ = null;
        }
        return conteudoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:messagemq.Mensagem)
    }

    // @@protoc_insertion_point(class_scope:messagemq.Mensagem)
    private static final messagemq.MessageProto.Mensagem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new messagemq.MessageProto.Mensagem();
    }

    public static messagemq.MessageProto.Mensagem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Mensagem>
        PARSER = new com.google.protobuf.AbstractParser<Mensagem>() {
      @java.lang.Override
      public Mensagem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Mensagem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Mensagem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public messagemq.MessageProto.Mensagem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConteudoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messagemq.Conteudo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>string tipo = 1;</code>
     * @return The tipo.
     */
    java.lang.String getTipo();
    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>string tipo = 1;</code>
     * @return The bytes for tipo.
     */
    com.google.protobuf.ByteString
        getTipoBytes();

    /**
     * <pre>
     * Sequência de bytes que compõe o corpo da mensagem
     * </pre>
     *
     * <code>bytes corpo = 2;</code>
     * @return The corpo.
     */
    com.google.protobuf.ByteString getCorpo();

    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>string nome = 3;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>string nome = 3;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();
  }
  /**
   * Protobuf type {@code messagemq.Conteudo}
   */
  public static final class Conteudo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:messagemq.Conteudo)
      ConteudoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        Conteudo.class.getName());
    }
    // Use Conteudo.newBuilder() to construct.
    private Conteudo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Conteudo() {
      tipo_ = "";
      corpo_ = com.google.protobuf.ByteString.EMPTY;
      nome_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messagemq.MessageProto.internal_static_messagemq_Conteudo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messagemq.MessageProto.internal_static_messagemq_Conteudo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messagemq.MessageProto.Conteudo.class, messagemq.MessageProto.Conteudo.Builder.class);
    }

    public static final int TIPO_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object tipo_ = "";
    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>string tipo = 1;</code>
     * @return The tipo.
     */
    @java.lang.Override
    public java.lang.String getTipo() {
      java.lang.Object ref = tipo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>string tipo = 1;</code>
     * @return The bytes for tipo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTipoBytes() {
      java.lang.Object ref = tipo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CORPO_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString corpo_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Sequência de bytes que compõe o corpo da mensagem
     * </pre>
     *
     * <code>bytes corpo = 2;</code>
     * @return The corpo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCorpo() {
      return corpo_;
    }

    public static final int NOME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nome_ = "";
    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>string nome = 3;</code>
     * @return The nome.
     */
    @java.lang.Override
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>string nome = 3;</code>
     * @return The bytes for nome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tipo_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, tipo_);
      }
      if (!corpo_.isEmpty()) {
        output.writeBytes(2, corpo_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nome_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, nome_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tipo_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, tipo_);
      }
      if (!corpo_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, corpo_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nome_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, nome_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof messagemq.MessageProto.Conteudo)) {
        return super.equals(obj);
      }
      messagemq.MessageProto.Conteudo other = (messagemq.MessageProto.Conteudo) obj;

      if (!getTipo()
          .equals(other.getTipo())) return false;
      if (!getCorpo()
          .equals(other.getCorpo())) return false;
      if (!getNome()
          .equals(other.getNome())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIPO_FIELD_NUMBER;
      hash = (53 * hash) + getTipo().hashCode();
      hash = (37 * hash) + CORPO_FIELD_NUMBER;
      hash = (53 * hash) + getCorpo().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static messagemq.MessageProto.Conteudo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messagemq.MessageProto.Conteudo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messagemq.MessageProto.Conteudo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messagemq.MessageProto.Conteudo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messagemq.MessageProto.Conteudo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messagemq.MessageProto.Conteudo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messagemq.MessageProto.Conteudo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static messagemq.MessageProto.Conteudo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static messagemq.MessageProto.Conteudo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static messagemq.MessageProto.Conteudo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static messagemq.MessageProto.Conteudo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static messagemq.MessageProto.Conteudo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(messagemq.MessageProto.Conteudo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messagemq.Conteudo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messagemq.Conteudo)
        messagemq.MessageProto.ConteudoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messagemq.MessageProto.internal_static_messagemq_Conteudo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messagemq.MessageProto.internal_static_messagemq_Conteudo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messagemq.MessageProto.Conteudo.class, messagemq.MessageProto.Conteudo.Builder.class);
      }

      // Construct using messagemq.MessageProto.Conteudo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        tipo_ = "";
        corpo_ = com.google.protobuf.ByteString.EMPTY;
        nome_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messagemq.MessageProto.internal_static_messagemq_Conteudo_descriptor;
      }

      @java.lang.Override
      public messagemq.MessageProto.Conteudo getDefaultInstanceForType() {
        return messagemq.MessageProto.Conteudo.getDefaultInstance();
      }

      @java.lang.Override
      public messagemq.MessageProto.Conteudo build() {
        messagemq.MessageProto.Conteudo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public messagemq.MessageProto.Conteudo buildPartial() {
        messagemq.MessageProto.Conteudo result = new messagemq.MessageProto.Conteudo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(messagemq.MessageProto.Conteudo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.tipo_ = tipo_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.corpo_ = corpo_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.nome_ = nome_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messagemq.MessageProto.Conteudo) {
          return mergeFrom((messagemq.MessageProto.Conteudo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messagemq.MessageProto.Conteudo other) {
        if (other == messagemq.MessageProto.Conteudo.getDefaultInstance()) return this;
        if (!other.getTipo().isEmpty()) {
          tipo_ = other.tipo_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getCorpo() != com.google.protobuf.ByteString.EMPTY) {
          setCorpo(other.getCorpo());
        }
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                tipo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                corpo_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                nome_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object tipo_ = "";
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>string tipo = 1;</code>
       * @return The tipo.
       */
      public java.lang.String getTipo() {
        java.lang.Object ref = tipo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tipo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>string tipo = 1;</code>
       * @return The bytes for tipo.
       */
      public com.google.protobuf.ByteString
          getTipoBytes() {
        java.lang.Object ref = tipo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tipo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>string tipo = 1;</code>
       * @param value The tipo to set.
       * @return This builder for chaining.
       */
      public Builder setTipo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        tipo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>string tipo = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTipo() {
        tipo_ = getDefaultInstance().getTipo();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>string tipo = 1;</code>
       * @param value The bytes for tipo to set.
       * @return This builder for chaining.
       */
      public Builder setTipoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        tipo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString corpo_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       *
       * <code>bytes corpo = 2;</code>
       * @return The corpo.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCorpo() {
        return corpo_;
      }
      /**
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       *
       * <code>bytes corpo = 2;</code>
       * @param value The corpo to set.
       * @return This builder for chaining.
       */
      public Builder setCorpo(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        corpo_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       *
       * <code>bytes corpo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCorpo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        corpo_ = getDefaultInstance().getCorpo();
        onChanged();
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>string nome = 3;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>string nome = 3;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>string nome = 3;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nome_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>string nome = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        nome_ = getDefaultInstance().getNome();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>string nome = 3;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nome_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messagemq.Conteudo)
    }

    // @@protoc_insertion_point(class_scope:messagemq.Conteudo)
    private static final messagemq.MessageProto.Conteudo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new messagemq.MessageProto.Conteudo();
    }

    public static messagemq.MessageProto.Conteudo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Conteudo>
        PARSER = new com.google.protobuf.AbstractParser<Conteudo>() {
      @java.lang.Override
      public Conteudo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Conteudo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Conteudo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public messagemq.MessageProto.Conteudo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messagemq_Mensagem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messagemq_Mensagem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messagemq_Conteudo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messagemq_Conteudo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/proto/Messages.proto\022\tmessage" +
      "mq\"m\n\010Mensagem\022\017\n\007emissor\030\001 \001(\t\022\014\n\004data\030" +
      "\002 \001(\t\022\014\n\004hora\030\003 \001(\t\022\r\n\005grupo\030\004 \001(\t\022%\n\010co" +
      "nteudo\030\005 \001(\0132\023.messagemq.Conteudo\"5\n\010Con" +
      "teudo\022\014\n\004tipo\030\001 \001(\t\022\r\n\005corpo\030\002 \001(\014\022\014\n\004no" +
      "me\030\003 \001(\tB\016B\014MessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_messagemq_Mensagem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messagemq_Mensagem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messagemq_Mensagem_descriptor,
        new java.lang.String[] { "Emissor", "Data", "Hora", "Grupo", "Conteudo", });
    internal_static_messagemq_Conteudo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messagemq_Conteudo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messagemq_Conteudo_descriptor,
        new java.lang.String[] { "Tipo", "Corpo", "Nome", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
